# Generated by Django 4.2.3 on 2023-12-03 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_task"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Task",
        ),
    ]
